<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_bag_play_tool</name>
  <version>0.1.0</version>
  <description>Qt-based ROS 2 bag playback and topic interruption tool.</description>

  <maintainer email="huangxiaoshuai@example.com">huangxiaoshuai</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <depend>rosgraph_msgs</depend>
  <depend>rosidl_typesupport_introspection_cpp</depend>
  <depend>qt_gui_cpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
